import Link from "next/link";
import { ArrowLeft, FileText } from "lucide-react";

export const metadata = {
  title: "Terms of Service — AskZero",
  description:
    "The terms you agree to when using AskZero, including credits, refunds, and acceptable use.",
};

const UPDATED = "31 August 2026";

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-14">
      <Link
        href="/chat"
        className="press mb-8 inline-flex items-center gap-1.5 text-[13px] font-medium text-text-tertiary transition-colors hover:text-foreground"
      >
        <ArrowLeft className="h-4 w-4" />
        Back to AskZero
      </Link>

      <div className="mb-3 flex items-center gap-2 text-accent">
        <FileText className="h-5 w-5" />
        <span className="text-[12px] font-semibold uppercase tracking-[0.14em]">
          Terms of Service
        </span>
      </div>
      <h1 className="text-3xl font-bold tracking-tight text-foreground">
        Terms of Service
      </h1>
      <p className="mt-3 text-[15px] leading-relaxed text-text-secondary">
        By creating an account or using AskZero, you agree to these terms. Last
        updated {UPDATED}.
      </p>

      <div className="mt-10 space-y-9">
        <Block title="What AskZero is">
          <p>
            AskZero gives you access to third-party AI models on a pay-per-use
            basis, and issues a cryptographically verifiable receipt for each
            answer. You need an account, and you need credits to send requests.
          </p>
        </Block>

        <Block title="Your account">
          <p>
            You must be old enough to enter a contract where you live, and at
            least 13. Keep your login secure — activity under your account is
            your responsibility. One person, one account; do not share access or
            resell it.
          </p>
        </Block>

        <Block title="Credits, payments, and refunds">
          <ul className="list-disc space-y-1.5 pl-5">
            <li>
              Credits are prepaid and spent per request. What a request costs
              depends on the model and the length of the exchange, and is shown
              on its receipt.
            </li>
            <li>
              Credits are not money, earn no interest, and cannot be transferred
              or cashed out.
            </li>
            <li>
              Unused credits are refundable on request within 14 days of
              purchase. Credits already spent are not, since the underlying
              compute has been paid for.
            </li>
            <li>
              If a request fails through our fault, the credits for it are
              returned to your balance.
            </li>
            <li>
              Crypto deposits are settled on-chain and are irreversible once
              confirmed. Send only to the address shown, on the network shown.
            </li>
          </ul>
        </Block>

        <Block title="Acceptable use">
          <p>Do not use AskZero to:</p>
          <ul className="mt-2 list-disc space-y-1.5 pl-5">
            <li>break the law, or help someone else do so;</li>
            <li>
              generate content that sexualizes minors, incites violence, or
              harasses a specific person;
            </li>
            <li>
              build malware, run intrusion or phishing campaigns, or target
              systems you are not authorized to test;
            </li>
            <li>
              scrape, resell, or automate access outside your own use of the
              product;
            </li>
            <li>
              deliberately evade rate limits, spend controls, or account
              restrictions.
            </li>
          </ul>
          <p className="mt-3">
            We may suspend an account for a serious or repeated breach. Where we
            do, unspent credits are refunded unless the breach involved fraud.
          </p>
        </Block>

        <Block title="What the models produce">
          <p>
            Answers are generated by third-party models and{" "}
            <b>can be wrong, outdated, or misleading</b>. Check anything you rely
            on. AskZero is not a substitute for professional medical, legal, or
            financial advice. A receipt proves an answer was not altered after it
            was produced — it does not certify that the answer is correct.
          </p>
        </Block>

        <Block title="Your content">
          <p>
            You keep ownership of what you write and what the models produce for
            you. You grant us only the permission needed to run the service —
            processing your requests, storing your history, and building your
            memory. See the{" "}
            <Link href="/privacy" className="font-medium text-accent hover:underline">
              Privacy Policy
            </Link>{" "}
            for what that entails, including the parts written permanently to a
            public network.
          </p>
        </Block>

        <Block title="Availability and liability">
          <p>
            AskZero is provided as-is. We do not guarantee uninterrupted service,
            and we depend on providers we do not control. To the extent the law
            allows, our total liability to you is capped at what you paid us in
            the three months before the claim.
          </p>
        </Block>

        <Block title="Changes and contact">
          <p>
            We may update these terms; material changes will be announced in the
            app before they take effect. Questions:{" "}
            <a
              href="mailto:support@askzero.ai"
              className="font-medium text-accent hover:underline"
            >
              support@askzero.ai
            </a>
            .
          </p>
        </Block>
      </div>
    </main>
  );
}

function Block({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <h2 className="mb-2 text-[15px] font-semibold text-foreground">{title}</h2>
      <div className="text-[14px] leading-relaxed text-text-secondary">
        {children}
      </div>
    </section>
  );
}
